name: Build Plugins

on:
  push:
    branches:
      - main
      - backend-builder
    paths:
      - "plugins/**"
      - ".github/workflows/build-plugins.yml"
      - "decky-build-plugin/**"
  pull_request:
    branches: ['*']
  workflow_dispatch:
    inputs:
      upload:
        type: boolean
        required: false
        description: Re-upload the plugins to the store

jobs:
  build:
    name: Build updated plugins
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/steamdeckhomebrew/holo-base:latest
    steps:
      - name: Update dependencies
        run: sudo pacman -S --noconfirm git python python-pip python-setuptools jdk11-openjdk

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: "recursive"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.9
        with:
          sha: ${{ github.sha }}
          separator: ","
          files: |
            plugins/*
            .github/workflows/build-plugins.yml

      - name: Build and upload plugins
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --stacktrace
        env:
          PLUGIN_STORE_KEY: ${{ secrets.PLUGIN_STORE_KEY }}
          PLUGIN_STORE_UPLOAD: ${{ github.ref == 'refs/heads/main' && (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.upload)) }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
